name       : perl-extutils-pkgconfig
version    : 1.16
release    : 3
source     :
    - http://search.cpan.org/CPAN/authors/id/X/XA/XAOC/ExtUtils-PkgConfig-1.16.tar.gz : bbeaced995d7d8d10cfc51a3a5a66da41ceb2bc04fedcab50e10e6300e801c6e
license    : LGPL-2.1
component  : programming.perl
summary    : simplistic interface to pkg-config
description: |
    The pkg-config program retrieves information about installed libraries, usually for the purposes of compiling against and linking to them
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
